<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework> <!-- Залишаємо .NET 10! -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Пакет Roslyn компілятора -->
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
    
    <!-- Офіційна бібліотека Facepunch (робоча версія з NuGet.org) -->
    <PackageReference Include="Facepunch.AssemblySchema" Version="1.0.13" />
  </ItemGroup>



  <ItemGroup>
    <!-- 
      ІГНОРУЄМО ВСІ .cs ФАЙЛИ В КОРЕНІ (крім Program.cs),
      щоб ваші тестові файли не заважали збирати саму утиліту.
    -->
    <Compile Remove="temp_api_stub.cs"/>
    
    <Compile Remove="*-test.cs" />
    <Compile Remove="*test*.cs" />
    <Compile Remove="Formulas-test.cs" />
    <Compile Remove="GameMetadata-test.cs" />
    <Compile Remove="ProgressionMath-test.cs" />
    <Compile Remove="StatRegistry-test.cs" />
    <Compile Remove="ShopMaster.razor" />
    <Compile Remove="ShopTowerPanel.razor" />
    <Compile Remove="UpgradeNode.razor" />
  </ItemGroup>

</Project>